
// To lazy load a route:
// 1. Dynamic import
// 2. React Suspense

export default function LazyLoad() {
    return <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultrices eu sapien ac varius. In ultricies ipsum iaculis, dignissim nisl ac, ullamcorper erat. Nulla ac mi venenatis, congue felis eget, iaculis urna. Morbi luctus euismod tortor, ac accumsan erat pretium et. Nulla commodo et augue sed varius. Nunc vel pulvinar nulla. In non mauris egestas neque dictum consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam in tortor dolor. Mauris augue dolor, lobortis et risus vel, posuere consectetur nulla. Aliquam mollis vitae purus non accumsan. Nunc feugiat tempus volutpat. Etiam luctus sollicitudin fringilla.

Integer nibh leo, hendrerit vitae ligula non, faucibus facilisis ipsum. Mauris gravida congue mi non commodo. Praesent nec gravida mauris. Aliquam tristique tellus lacinia est facilisis pretium. Maecenas odio lorem, euismod quis felis et, molestie tristique dui. Integer dolor diam, fringilla nec leo at, posuere pretium arcu. Donec laoreet in sapien nec mollis. Etiam mollis placerat justo eget malesuada. Nullam facilisis neque ut enim hendrerit tincidunt.

Proin viverra nisl id ex ullamcorper pharetra sed eu enim. Nunc dapibus ac nibh sit amet venenatis. Cras ut urna dignissim, condimentum leo ut, porta mi. Ut finibus blandit est, in imperdiet dui. Etiam suscipit tortor arcu, sed ultrices dolor viverra vel. Donec nec mollis nibh. Suspendisse rutrum, velit a ullamcorper pulvinar, ipsum nunc pulvinar eros, ac tincidunt lacus orci vitae arcu. Pellentesque commodo placerat varius. In hac habitasse platea dictumst.

Sed quis urna quis augue consequat cursus. Sed dictum arcu nec massa tincidunt, quis tempus ligula sodales. Aenean ultrices tellus vel ex scelerisque imperdiet. Mauris eget iaculis elit. Morbi non finibus eros, a porttitor ligula. Nullam feugiat molestie interdum. Nulla at arcu sit amet nulla lacinia posuere eu in leo. Aliquam vehicula tellus in lorem feugiat ullamcorper. Quisque ac suscipit nulla. Suspendisse id sem cursus, luctus augue quis, euismod ligula. Etiam varius nisl at orci dignissim pulvinar. Nullam nibh magna, laoreet at risus a, blandit molestie sapien.

Phasellus sem purus, porttitor sit amet metus non, bibendum rhoncus tellus. Morbi sit amet congue turpis. Ut sem lectus, cursus nec placerat ut, ullamcorper quis est. Integer auctor ac felis in condimentum. Nullam eget hendrerit neque. Nam aliquet eros nec nulla cursus, ac aliquet ipsum auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur viverra feugiat mi vitae volutpat. Fusce nulla urna, ornare vel orci id, porta mattis risus. Donec dignissim mi fermentum, aliquet est at, scelerisque nisi. Aliquam at turpis eleifend, tristique leo sit amet, hendrerit dolor. Vestibulum pulvinar magna nec sapien semper, non suscipit urna auctor. Nunc in lorem a purus pulvinar imperdiet in ac enim. Donec ut neque commodo, egestas tellus a, tincidunt massa. Phasellus id lorem sit amet urna gravida bibendum sit amet in odio. Quisque volutpat, quam ut pharetra pharetra, magna metus pretium mauris, vel tempus lacus est euismod libero.

Fusce pretium dignissim blandit. Phasellus pulvinar posuere urna, nec malesuada tellus pellentesque dignissim. Donec feugiat, dui vitae ultricies blandit, lectus mi malesuada magna, in placerat libero nulla vel dolor. In leo erat, elementum in dapibus euismod, viverra quis justo. Mauris elit lacus, ultrices nec orci sed, suscipit mollis eros. Sed auctor arcu in vestibulum consectetur. Duis vel aliquam erat. Suspendisse et nunc at augue posuere sollicitudin non vel enim. Nam lobortis blandit augue, in posuere mauris iaculis id. Aenean scelerisque lacus nec dolor imperdiet aliquet ut in est. Mauris vitae arcu efficitur, vehicula lorem tempus, scelerisque turpis. Morbi est dui, rutrum id feugiat vitae, bibendum eget quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean dui ante, lobortis sit amet leo et, sagittis dignissim tortor. Suspendisse aliquam risus at ex iaculis, finibus fringilla lacus malesuada.

Duis urna elit, vulputate id lacus a, volutpat ullamcorper lacus. Donec at interdum lacus, non egestas erat. Phasellus magna orci, condimentum at tincidunt in, ultrices ut risus. Aliquam et egestas risus. Sed vestibulum est sodales, congue turpis sed, posuere lectus. Curabitur pellentesque, turpis ac vulputate aliquet, arcu libero mattis eros, in vulputate metus ante ac ex. Suspendisse euismod orci ut purus rutrum, sit amet blandit lorem feugiat. Sed semper orci arcu, nec placerat arcu commodo vel. Donec ornare est vel lectus euismod, id varius nisi consectetur. Pellentesque egestas lectus at elit congue efficitur. Integer sed nisl id erat egestas sollicitudin.

Nam ut porta ex. Cras ornare venenatis sodales. Maecenas aliquet nulla dui, vitae ornare ex fringilla ut. Nam maximus tincidunt quam, at viverra libero dapibus sit amet. Ut ultrices vulputate purus a rutrum. Praesent dui magna, accumsan ac sagittis non, eleifend in est. Vestibulum ultricies metus et bibendum ullamcorper. Integer mollis a felis et luctus. Cras et vehicula tellus. Suspendisse potenti. Morbi mattis convallis pharetra. Pellentesque molestie urna magna, eget maximus tellus congue vel. Praesent vehicula, mauris non porttitor molestie, odio tortor gravida enim, eu facilisis purus dolor at massa. Vestibulum pellentesque, elit non porta vulputate, neque sapien sagittis est, nec egestas eros ante a ex. Ut ornare leo nec nulla elementum, nec venenatis lectus interdum.

Donec in quam neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc eget semper arcu. Etiam bibendum leo diam, a tincidunt nisi tristique in. Duis pulvinar hendrerit neque et aliquet. Proin aliquet urna sit amet dictum vestibulum. Duis sodales justo nisl, at suscipit neque molestie sit amet. Sed scelerisque erat id rhoncus maximus. Duis lorem ligula, tempus quis viverra nec, facilisis at augue. Mauris egestas, odio a dapibus venenatis, leo ante malesuada dui, eget blandit ipsum ipsum ac eros. Fusce orci sapien, commodo eu turpis eget, sagittis hendrerit augue. Maecenas egestas bibendum neque, id iaculis magna molestie ultrices. Phasellus dolor nulla, vestibulum a est at, pulvinar finibus lacus. Suspendisse vitae ultrices urna, venenatis scelerisque libero. Suspendisse posuere erat a mauris rutrum lobortis.

Nunc suscipit nisl diam, nec efficitur mauris laoreet ut. Phasellus faucibus tellus eu rhoncus hendrerit. Praesent accumsan mi elit, nec aliquam erat pulvinar in. Curabitur lacus erat, porttitor ut tortor a, faucibus elementum sem. Curabitur sodales eu arcu ut tristique. In pulvinar ipsum sit amet est sollicitudin lacinia. In porttitor sed erat ut semper. Nam venenatis euismod quam ac pellentesque. Donec ornare libero eros, nec pharetra urna imperdiet in. Cras scelerisque bibendum urna. Suspendisse pulvinar dolor tortor, nec fringilla nisi posuere mollis. Phasellus aliquet sagittis posuere. Integer sit amet mollis arcu, ac dapibus erat. Vivamus at viverra diam. Etiam ac gravida turpis.

Mauris sit amet enim sed elit pretium vehicula id nec massa. Vestibulum ac risus eget lacus aliquam cursus in vitae ante. Donec hendrerit, sapien sed ornare mattis, nisi eros condimentum nulla, sed sagittis urna lorem vel enim. Donec iaculis elit augue, vitae bibendum sapien sodales ac. Nullam placerat nisl dignissim nulla pulvinar, at tristique quam ornare. Donec eget volutpat sem. Etiam quam justo, porta quis nulla eu, ornare ultrices nisl. Suspendisse in velit congue purus accumsan viverra nec id tortor. Praesent egestas ligula non dolor mollis, sit amet tempor ipsum iaculis.

Praesent dolor lorem, hendrerit in fermentum eget, tempus ac nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas imperdiet, turpis sit amet gravida consequat, ipsum felis accumsan lacus, non egestas ex nunc id odio. In nibh risus, euismod quis urna sit amet, sodales ultricies ex. Etiam sit amet ante quam. Praesent tortor neque, varius ac porttitor et, volutpat ac nulla. Proin aliquam lectus id libero consequat scelerisque. Suspendisse orci lorem, luctus id vulputate a, ultricies et leo.

Nam semper viverra lacus eget eleifend. Praesent rutrum bibendum neque sit amet egestas. Ut malesuada feugiat eros vitae bibendum. Morbi nulla purus, tempus non lorem non, sodales lacinia ipsum. Morbi sit amet tincidunt lectus. Praesent libero sem, pharetra et tempor sed, ultricies sed eros. Maecenas fringilla quam lectus, eu interdum turpis varius eget. Sed odio nibh, mattis non mauris vitae, interdum fringilla elit. Sed eleifend feugiat diam et volutpat.

Cras tempus turpis sit amet ligula tempus pulvinar. Aenean imperdiet rutrum nisi sed blandit. Nulla aliquam, ex posuere commodo sagittis, erat elit tempus erat, sed malesuada dui elit non mauris. Integer efficitur augue dolor, quis consectetur diam finibus nec. Donec ornare sollicitudin nisi, eu vehicula enim consectetur ac. Pellentesque laoreet pellentesque orci, a congue lacus egestas nec. Integer et libero pretium, tristique ex ac, mollis diam. Cras eu nulla aliquet, condimentum erat eget, vehicula enim. Vestibulum laoreet, felis in mollis congue, lectus dolor commodo tortor, ac tristique turpis magna sit amet ligula. Proin a ultrices odio. Curabitur ante ligula, venenatis id risus et, eleifend faucibus elit. Sed in ornare tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec consequat mollis lorem, nec ornare dolor faucibus et.

Nullam consectetur nulla vel sapien aliquam dictum. Suspendisse potenti. Fusce sit amet turpis eget ex ullamcorper commodo. Ut gravida, est ut maximus euismod, mi lectus vulputate turpis, tincidunt commodo metus ex eu sem. Nulla gravida ligula quis iaculis rutrum. Nullam congue est vitae est maximus sollicitudin. Nulla tincidunt nec lectus et sodales. Mauris dui urna, ullamcorper a turpis nec, volutpat porta justo. Nullam mattis tortor at nisi varius, quis lacinia enim porttitor. Suspendisse scelerisque enim nec massa suscipit, in iaculis urna vehicula. Morbi condimentum malesuada finibus.

Nulla felis eros, rutrum in sem sed, facilisis auctor nulla. Cras in neque ligula. Fusce rhoncus ultricies mauris. Ut efficitur tempor ex, at varius augue facilisis ac. Cras sit amet mollis est. Suspendisse libero magna, sodales eget ante sit amet, blandit posuere elit. Cras condimentum dapibus nunc sit amet iaculis. Aenean posuere nisl vitae sollicitudin tempor. Sed ut sagittis justo. Proin posuere dolor at justo rutrum auctor. Fusce interdum vulputate magna, ullamcorper venenatis dui. Donec ac fermentum quam, eu dignissim elit. Proin dignissim ipsum eget metus imperdiet, sed facilisis enim facilisis.

Vestibulum commodo tortor at justo consequat facilisis. Integer congue sodales nisi non iaculis. Donec sagittis lorem a pharetra rhoncus. Ut dignissim et dui nec interdum. Maecenas tempor ut velit non lobortis. Aliquam vel sagittis nunc. Sed egestas et lorem non cursus. Curabitur quis scelerisque erat.

Suspendisse tortor lorem, euismod sagittis iaculis sit amet, consequat in mauris. Suspendisse potenti. Vestibulum tempus porta ante sed blandit. Duis non quam sed lectus facilisis laoreet faucibus non mauris. Ut vel posuere lectus. Aliquam luctus augue eu mauris imperdiet, interdum accumsan nulla placerat. Cras et volutpat diam. Phasellus enim elit, euismod vitae sagittis sit amet, ullamcorper sit amet arcu. Mauris vel viverra tellus, posuere ullamcorper nisi. Curabitur non diam id ligula tempus aliquet. Ut risus massa, efficitur in egestas sit amet, egestas ac est. Vivamus cursus nisl lectus, eu dapibus odio feugiat ut. Etiam at tortor sagittis, finibus diam eu, tincidunt ex. Sed imperdiet felis eget orci posuere, nec blandit metus ullamcorper. Vestibulum porttitor blandit diam ac accumsan.

Curabitur nibh nisl, ultrices sit amet ante in, eleifend aliquet nunc. Nam at venenatis metus. Vestibulum cursus tellus feugiat malesuada congue. Aenean accumsan elementum lectus nec aliquet. Vivamus egestas metus quis molestie ullamcorper. Donec finibus in diam at tristique. Integer vitae libero vel erat imperdiet cursus nec a felis. Nullam dictum facilisis lorem, et ornare nulla tempor eu. Maecenas maximus elit pharetra urna congue, ac fringilla sem consequat. Sed eget est sit amet est vehicula ultricies. Pellentesque convallis suscipit commodo. Quisque commodo, libero a ornare maximus, lectus libero blandit purus, eget luctus risus dolor et velit. Aenean interdum vitae neque ut cursus. Nulla cursus quam gravida tellus commodo, ac posuere dolor dapibus. Mauris scelerisque orci in turpis vestibulum sollicitudin.

Maecenas efficitur est eget nibh tempus, quis laoreet nulla ultrices. Phasellus eu sapien non est suscipit consequat sit amet quis lorem. Aliquam varius sed lacus vitae commodo. In hac habitasse platea dictumst. Fusce nec mauris nec sapien pulvinar vulputate ut sit amet arcu. Praesent ornare, quam eget suscipit porttitor, purus enim tincidunt massa, eget sollicitudin purus dui eu augue. Nunc vitae leo ultricies, mattis elit a, luctus tellus. Vivamus interdum risus a malesuada elementum. Maecenas congue tempor enim, iaculis vulputate lorem viverra id. Duis iaculis fringilla neque, eu pretium diam consequat non. Ut sit amet ligula ac metus aliquam efficitur a sit amet neque. Ut eget urna et erat consequat cursus. Aenean auctor ut nulla ut ultrices. Fusce ac convallis felis.
    </div>
}